In [19]:
import pandas as pd
import numpy as np
df = pd.read_csv("data_222_13032026.csv")


df_copy = df.copy()
#df_copy

df_copy['shutheight'] = (
    df_copy['shutheight']
        .replace(0, np.nan)
        .bfill()
)

# df_copy
df_final = (
    df_copy
        .groupby('epc', as_index=False)
        .agg({'hourly_count': 'sum'})
)
# df_final = (
#     df_copy
#         .groupby(['hour_ist', 'epc', 'shutheight'], as_index=False)
#         .agg({'hourly_count': 'sum'})
# )


# df_final
# df_final = df_final.sort_values('hour_ist')
df_final

                        epc  hourly_count
0  e00000000000000000000236          1805

In [3]:
epc_value = "e200471690406821a3010110"

df_filtered = df_final[df_final['epc'] == epc_value]

df_filtered

               hour_ist                       epc  shutheight  hourly_count
0   2026-02-26 09:00:00  e200471690406821a3010110      320.07           289
1   2026-02-26 10:00:00  e200471690406821a3010110      320.07           349
2   2026-02-26 11:00:00  e200471690406821a3010110      320.07           195
3   2026-02-26 12:00:00  e200471690406821a3010110      320.07            95
4   2026-02-26 13:00:00  e200471690406821a3010110      320.07           225
5   2026-02-26 14:00:00  e200471690406821a3010110      320.07           196
6   2026-02-26 15:00:00  e200471690406821a3010110      320.07           218
8   2026-02-26 16:00:00  e200471690406821a3010110      320.07           140
15  2026-02-26 18:00:00  e200471690406821a3010110      319.87             2
16  2026-02-26 18:00:00  e200471690406821a3010110      320.01             2
17  2026-02-26 18:00:00  e200471690406821a3010110      320.18             2
18  2026-02-26 18:00:00  e200471690406821a3010110      320.73             1
19  2026-02-26 18:00:00  e200471690406821a3010110      321.77             1
20  2026-02-26 18:00:00  e200471690406821a3010110      323.19             1
21  2026-02-26 18:00:00  e200471690406821a3010110      324.58             1
22  2026-02-26 18:00:00  e200471690406821a3010110      337.43             2
23  2026-02-26 20:00:00  e200471690406821a3010110      319.87           125
24  2026-02-26 21:00:00  e200471690406821a3010110      319.87           247

In [4]:
df_final[df_final['epc'] == epc_value]['hourly_count'].sum()

np.int64(2091)

In [5]:
epc_value = "e200471670a06821a107010d"

df_filtered = df_final[df_final['epc'] == epc_value]

df_filtered

df_final[df_final['epc'] == epc_value]['hourly_count'].sum()

np.int64(207)